version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    container_name: sqmusic_main
    environment:
      - DB_IP=mysql
      - DB_PORT=3306
      - DB_NAME=sqmusicv3
      - DB_USERNAME=root
      - DB_PASSWORD=sqmusicv3password
    volumes:
      - ./music:/music
    depends_on:
      - mysql
    networks:
      - sq-app-network
    expose:
      - "8099"

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
      args:
        - NODE_OPTIONS=--max-old-space-size=4096
    container_name: sqmusic_web
    networks:
      - sq-app-network
    expose:
      - "80"

  mysql:
    image: mysql:5.7
    container_name: sqmusic_mysql
    environment:
      MYSQL_ROOT_PASSWORD: sqmusicv3password
      MYSQL_DATABASE: sqmusicv3
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sq-app-network

  nginx:
    image: nginx:alpine
    container_name: sqmusic_nginx
    ports:
      - "8096:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - sq-app-network

networks:
  sq-app-network:
    driver: bridge

volumes:
  mysql_data: