name: Java CI with Maven and Release

on:
  push:
    branches: [ "3.0" ] # 只在提交到3.0分支时触发

env:
  APP_VERSION: ""
  DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
  DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' # optional
      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.16.2/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      - name: Read Application Version
        id: app_version
        run: |
          VERSION=$(cd src/main/resources && yq e '.version' application.yml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          echo "APP_VERSION: $VERSION"
          echo "$VERSION" > version.txt
      - name: List Environment Variables
        run: env
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
      - name: Get JAR file name
        id: jar_name
        run: |
          JAR_FILE=$(ls target/*.jar | grep -v sources | head -n 1)
          JAR_FILE=$(basename $JAR_FILE)
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
          echo "jar_file=$JAR_FILE" >> $GITHUB_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-artifact
          path: |
            target/*.jar 
            version.txt
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        run: |
          # 登录阿里云镜像仓库
          echo $DOCKER_PASSWORD | docker login registry.cn-hangzhou.aliyuncs.com --username=$DOCKER_USERNAME --password-stdin
          
          # 登录 GitHub Packages
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # 构建并推送主应用镜像
          docker buildx create --use
          docker buildx build --push \
            --tag registry.cn-hangzhou.aliyuncs.com/sqdockler/sq_docker:v$APP_VERSION \
            --tag registry.cn-hangzhou.aliyuncs.com/sqdockler/sq_docker:latest \
            -f Dockerfile .
          
          # 构建并推送GitHub Packages镜像
          docker buildx build --push \
            --tag ghcr.io/${{ github.actor }}/simple_sq_musuc_plus:v$APP_VERSION \
            --tag ghcr.io/${{ github.actor }}/simple_sq_musuc_plus:latest \
            -f Dockerfile .

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: java-artifact
      - name: Display structure of downloaded files
        run: ls -R
      - name: Read Version from Artifact
        id: app_version
        run: |
          VERSION=$(cat version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "APP_VERSION: $VERSION"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.app_version.outputs.version }}
          release_name: Release ${{ steps.app_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.JAR_FILE }}
          asset_name: ${{ env.JAR_FILE }}
          asset_content_type: application/octet-stream