name: Deploy Docsify to GitHub Pages

on:
  push:
    branches: [ 3.0 ]
    paths:
      - src/main/resources/docs/**

# 权限设置（必须）
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload docs folder
        uses: actions/upload-pages-artifact@v3
        with:
          # 关键：直接读取你原来的目录，不改任何结构！
          path: "src/main/resources/docs"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4